apiVersion: v1
appVersion: V.0.1
description: 'Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.'
name: edu
version: 0.1.0
home: edu.zaakonline.nl
icon: edu.zaakonline.nl