apiVersion: v1
entries:
  edu:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-10-12T11:46:49.47048Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 9c832adf3e7ba1c2100bbf7a99ef0e5a784abfb435f599fab9b2f562748cf569
    home: edu.zaakonline.nl
    icon: edu.zaakonline.nl
    name: edu
    urls:
    - edu-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-12T11:46:49.4630849Z"
